# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |box|
		box.customize ["modifyvm", :id, "--memory", "256"]
	end

	[ 'balancer', 'database', 'application-1', 'application-2' ].each do |name|
		config.vm.define "#{name}" do |box|
			box.vm.hostname         = "#{name}.vanilla.com"
			box.vm.box              = "centos/7"
			box.vm.box_check_update = false
			box.vm.network "private_network", type: "dhcp"
		end
	end

	config.vm.define "balancer" do |box|
		box.vm.network "forwarded_port",
			:guest => 80,
			:host  => 8080
	end

end
