# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
    config.vm.provider :virtualbox do |box|
        box.linked_clone = true
        box.customize [ "modifyvm", :id, "--memory", "1024", "--cpus", "1" ]
    end

    config.vm.define :master do |box|
        box.vm.hostname         = "master.vanilla.com"
        box.vm.box              = "centos/7"
        box.vm.box_check_update = false
        box.vm.synced_folder ".", "/vagrant"
        box.vm.network :private_network, :type => "dhcp"
       
        config.vm.provision "shell", 
            :path => "install-tools.sh"

        config.vm.provision :shell, 
            :path => "install-dns.sh", 
            :args => "master", 
            :preserve_order => true,
            :run => "always"
    end


    config.vm.define :puppet do |box|
        box.vm.hostname         = "puppet.vanilla.com"
        box.vm.box              = "centos/7"
        box.vm.box_check_update = false
        box.vm.synced_folder ".", "/vagrant"
        box.vm.network :private_network, :type => "dhcp"
       
        config.vm.provision "shell", 
            :path => "install-tools.sh"

        config.vm.provision :shell, 
            :path => "install-dns.sh", 
            :args => "slave", 
            :preserve_order => true,
            :run => "always"
    end


end
