---
- name: install and configure apache
  hosts: back
  become: yes

  tasks:
  - name: Install Apache
    yum:  name=httpd state=latest

  - name: Enable Apache
    service: name=httpd enabled=yes

  - name: Start Apache
    service: name=httpd state=started
