---
- name: install and configure nginx
  hosts: front
  become: yes

  tasks:
  - name: Install nginx
    yum:  name=nginx state=latest

  - name: Enable Nginx
    service: name=nginx enabled=yes

  - name: Copy Configuration
    force: yes
    copy: src=nginx.conf
          dest=/etc/nginx/nginx.conf

  - name: Start Nginx
    service: name=nginx state=started

  - name: Reload Nginx
    service: name=nginx state=reloaded

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
